name: Build Incus image
on:
  workflow_dispatch:

env:
  os: mageia

jobs:
  clean_old_repo:
    name: Clean old repo
    runs-on: self-hosted
    steps:
      - name: Clean old repo
        run: sudo rm -rf .* *
  clone_repo:
    name: Clone repo
    runs-on: self-hosted
    needs: clean_old_repo
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
  craft_minimal_system:
    name: Craft minimal system
    runs-on: self-hosted
    needs: clone_repo
    steps:
      - name: Make 'minimal-fs'
        run: make minimal-fs
  compress_filesystem_readonly:
    name: Compress filesystem read-only
    runs-on: self-hosted
    needs: craft_minimal_system
    steps:
      - name: Make 'squash-fs'
        run: make squash-fs
      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: ${{env.os}}.sqfs
          path: ${{env.os}}.sqfs
  build_for_target:
    name: Build for target
    runs-on: self-hosted
    needs: compress_filesystem_readonly
    steps:
      - name: Make target 'build-incus'
        run: make build-incus
      - name: Upload image
        uses: actions/upload-artifact@v3
        with:
          name: image-${{env.os}}-incus
          path: ./out
