name: Build LXC image
on:
  workflow_dispatch:

env:
  os: mageia

jobs:
  prepare_clean_repo:
    name: Prepare clean repo
    runs-on: self-hosted
    steps:
      - uses: Chiogros/prepare-clean-repo-action@main
  compress_filesystem_readonly:
    name: Compress filesystem read-only
    runs-on: self-hosted
    needs: prepare_clean_repo
    steps:
      - uses: ./.github/workflows/compress-filesystem-readonly.yaml
  build_for_target:
    name: Build for target
    runs-on: self-hosted
    needs: compress_filesystem_readonly
    steps:
      - name: Make target 'build-lxc'
        run: make build-lxc
      - uses: actions/upload-artifact@v3
        with:
          name: image-${{env.os}}-lxc
          path: ./out
