name: Build Incus image
on:
  workflow_dispatch:

env:
  os: mageia

jobs:
  clone-repo:
    name: Clone repo
    uses: ./.github/workflows/checkout-self-hosted.yaml

  build-rootfs:
    name: Build rootfs
    needs: clone-repo
    uses: ./.github/workflows/build-rootfs.yaml

  build-for-target:
    name: Build for target
    runs-on: self-hosted
    needs: build-rootfs
    steps:
      - name: Cache build
        id: build
        uses: actions/cache@v4
        with:
          path: ./out/disk.qcow2
          key: image-${{ env.os }}-incus-${{ hashFiles('*.sqfs', '*.yaml') }}
      - name: Make target 'build-incus'
        if: steps.build.outputs.cache-hit != 'true'
        run: make build-incus

      - name: Upload image
        uses: actions/upload-artifact@v4
        with:
          name: image-${{ env.os }}-incus
          path: ./out/*
