name: Compress filesystem read-only
on:
  workflow_dispatch:

env:
  os: mageia

jobs:
  compress_filesystem_readonly:
    name: Compress filesystem read-only
    runs-on: self-hosted
    steps:
      - name: Clean old repo
        run: sudo rm -rf .* *
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Craft minimal system
        uses: ./.github/workflows/craft-minimal-system.yaml
      - name: Make target 'squash-fs'
        uses: ./.github/workflows/compress-filesystem-readonly.yaml
      - name: Upload squashfs
        uses: ./.github/workflows/upload-squashfs.yaml
        with:
          name: ${{env.os}}.sqfs
          path: ${{env.os}}.sqfs
