name: Craft minimal system
on:
  workflow_dispatch:

env:
  os: mageia

jobs:
  craft_minimal_system:
    name: Craft minimal system 
    runs-on: self-hosted
    steps:
      - name: Clean old repo
        run: sudo rm -rf .* *
      - name: Clone repo
        uses: actions/checkout@v3 
      - name: Make target 'minimal-fs'
        uses: ./.github/workflows/runs/craft-minimal-system.yaml
