name: Craft minimal system
on:
  workflow_dispatch:

env:
  os: mageia

jobs:
  craft_minimal_system:
    name: Craft minimal system 
    runs-on: self-hosted
    steps:
      - name: Clean old repo
        uses: ./.github/workflows/runs/clean-old-repo.yaml
      - name: Clone repo
        uses: ./.github/workflows/runs/clone-repo.yaml
      - name: Make target 'minimal-fs'
        uses: ./.github/workflows/runs/craft-minimal-system.yaml
