name: Making LXC image
on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  clone_repo:
    name: Clone repo
    uses: GuillaumeFalourd/clone-github-repo-action/.github/workflows/public-repo.yml@v2.1
    with:
      owner: Chiogros
      repository: image-mageia-lxc
      depth: 1
  craft_minimal_system:
    name: Craft minimal system 
    runs-on: self-hosted
    steps:
      - name: Building FHS
        run: sudo rpm --rebuilddb --root=mageia

