name: Making LXC image
on:
  push:
    branches:
      - main
jobs:
  craft_minimal_system:
    name: Craft minimal system 
    runs-on: self-hosted
    steps:
      - name: Building FHS
        run: sudo rpm --rebuilddb --root=mageia
