name: Making LXC image
on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

env:
  os: mageia

jobs:
  clone_repo:
    name: Clone repo
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
  craft_minimal_system:
    name: Craft minimal system 
    runs-on: self-hosted
    needs: clone_repo
    steps:
      #- name: Create building environment
      #  run: mkdir ${{env.os}}
      #- name: Building FHS
      #  run: sudo rpm --rebuilddb --root=${GITHUB_WORKSPACE}/${{env.os}}
      - name: Make target 'minimal-fs'
        run: make minimal-fs
  compress_readonly_filesystem:
    name: Compress read-only filesystem
    runs-on: self-hosted
    needs: craft_minimal_system
    steps:
      - name: Make target 'squash-fs'
        run: make squash-fs
  build_for_target:
    name: Build for target
    runs-on: self-hosted
    needs: compress_readonly_filesystem
    steps:
      - name: Make target 'build'
        run: make build
#      - uses: actions/upload-artifact@v3
#        with:
#          name: ${{env.os}}${{env.ver}} LXC image
#          path: ${GITHUB_WORKSPACE}/${{env.os}}/${{env.os}}
