name: Making LXC image
on:
  workflow_dispatch:
#  push:
#    branches:
#      - main

jobs:
  clone_repo:
    name: Clone repo
    uses: ./.github/workflows/clone-repo.yaml
  craft_minimal_system:
    name: Craft minimal system 
    runs-on: self-hosted
    steps:
      - name: Create building environment
        run: mkdir mageia
      - name: Building FHS
        run: sudo rpm --rebuilddb --root=mageia

