name: Prepare clean repo
on:
  workflow_dispatch:

jobs:
  clean_repo:
    name: Clean old repo
    runs-on: self-hosted
    steps:
      - name: Clean old repo
        run: sudo rm -rf "$PWD/../${{github.event.repository.name}}"
  clone_repo:
    name: Clone repo
    runs-on: self-hosted
    needs: clean_repo
    steps:
      - uses: actions/checkout@v3
